# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: bash -c 'cd backend && ruff check --config=pyproject.toml --fix'
        language: system
        types_or: [python, pyi]
        pass_filenames: false
        require_serial: true

      - id: ruff-format
        name: ruff format
        entry: bash -c 'cd backend && ruff format --config=pyproject.toml'
        language: system
        types_or: [python, pyi]
        pass_filenames: false
        require_serial: true
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args:
          [
            --strict,
            --ignore-missing-imports,
            --config,
            "backend/pyproject.toml",
          ]
        files: ^backend/
        additional_dependencies:
          - alembic
          - fastapi
          - pydantic
          - pydantic-settings
          - sqlalchemy
          - gunicorn
          - types-PyJWT
          - pyjwt
          - passlib
          - types-passlib
          - bcrypt
          - argon2
