name: full-stack-fastapi-template

services:
  db:
    image: postgres:18.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      POSTGRES_DB: ${POSTGRES_DB?Variable not set}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - app-network
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4:9.10
    depends_on:
      - db
    ports:
      - "${PGADMIN_PORT?Variable not set}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL?Variable not set}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD?Variable not set}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network
    restart: unless-stopped
  backend:
      # ...
      # build in override/prod
    depends_on:
      - db
      - pgadmin
    ports:
      - "${BACKEND_PORT?Variable not set}:${BACKEND__GUNICORN__PORT?Variable not set}"
    environment:
      BACKEND__ENVIRONMENT: ${ENVIRONMENT?Variable not set}
      BACKEND__DATABASE__HOST: db
      BACKEND__DATABASE__PORT: 5432
      BACKEND__DATABASE__USER: ${POSTGRES_USER?Variable not set}
      BACKEND__DATABASE__USER_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      BACKEND__DATABASE__DB_NAME: ${POSTGRES_DB?Variable not set}      
    networks:
      - app-network
    restart: unless-stopped


volumes:
  pgdata:
  pgadmin-data:

networks:
  app-network: